### PR TITLE
Made rhs of classical assignment required

### PR DESCRIPTION
**Pull request by aspcompiler**
### Summary

Made rhs of classical assignment required

### Details and comments

Currently, the rhs in classical assignment is optional:

```
classicalAssignment
    : Identifier designator? ( assignmentOperator expression )?
    ;
```

This was determined to be a bug per [slack discussion](https://qiskit.slack.com/archives/G01KL989ADN/p1628117570011800).

### CODE REVIEW

**Review by jakelishman — APPROVED** [review]
Looks correct to me, and passes the tests (albeit after rebase onto `master` - I think this PR was branched off a pretty old version which had failing tests).  It'd probably be good to get some CI automation going here, to make sure we never break the tests accidentally.

**Comment by aspcompiler** [comment]
> Looks correct to me, and passes the tests (albeit after rebase onto `master` - I think this PR was branched off a pretty old version which had failing tests). It'd probably be good to get some CI automation going here, to make sure we never break the tests accidentally.

I merged with the current main branch. All test passed. Thanks for pointing out!

**Comment by taalexander** [comment]
Would you mind posting the Slack discussion (or a summary). I am unable to access this.

**Comment by aspcompiler** [comment]
@taalexander, here is the discussion:

**Li Chen** Aug 4th
I wonder why assignmentOperator expression in classicalAssignment is optional:
```
classicalAssignment
    : Identifier designator? ( assignmentOperator expression )?
    ;
```
I thought this must be a bug but Zack Schoenfeld made the explicit change on May 6.


**Steven Heidel  9 days ago**
This seems like a mistake. It's not declaring a variable since there's no type. I can't think of a reason for having a variable on its own line like this:
```myvar[0];```

...

**Michael Healy  8 days ago**
Good point, perhaps it should be:
```
classicalAssignment
    : Identifier designator? assignmentOperator expression
    ;
```

**Li Chen  8 days ago**
Agree :+1:

**Steven Heidel  8 days ago**
+1 - thanks all

**Pull request merged**
