### PR TITLE
Fix bug in complex grammar

### LINKED ISSUE #258: Bug with complex type?
### Informations

- **OpenQASM version**: 3.x
- **Python version**: 3.x
- **Operating system**: 3.x

### What is the current behavior?

There are a few potential issues with #175 merged on 8/16/2021.

```
singleDesignatorType
    : 'int'
    | 'uint'
    | 'float'
    | 'angle'
    | 'complex'
    ;

classicalType
    : singleDesignatorType designator
    | doubleDesignatorType doubleDesignator
    | noDesignatorType
    | bitType designator?
    | 'complex' LBRACKET numericType RBRACKET
    ;

// numeric OpenQASM types
numericType
    : singleDesignatorType designator
    | doubleDesignatorType doubleDesignator
    ;

classicalArgument
    :
    ...
    | 'complex' LBRACKET numericType designator RBRACKET Identifier
    ;
```
1. It appears that the  `complex` under `singleDesignatorType` is not needed. `classicalType` already contains a  branch for `complex`. 
2. It appears that the `complex` declaration under `classicalArgument` is not correct. The `designator` after `numericType` is not needed as `numericType` already has `designator`.

### Steps to reproduce the problem

See above.

### What is the expected behavior?

See above

### Suggested solutions

Make changes to these 2 rules:

```
singleDesignatorType
    : 'int'
    | 'uint'
    | 'float'
    | 'angle'
    ;

classicalArgument
    :
    ...
    | 'complex' LBRACKET numericType RBRACKET Identifier
    ;
```

### PR DESCRIPTION
**Pull request by taalexander**
### Summary
Closes #258. Implement fix suggested by @aspcompiler.

### CODE REVIEW

**Review by aspcompiler — APPROVED** [review]

**Review by jakelishman — APPROVED** [review]
Looks good to me as a fix.

The bug does seem to suggest that the way we split types in the grammar (no, single-, and double-designator types) might not be the best logical split.  Is it necessary for it to be a _parse_ error to have an incorrect number of arguments to a type?  We already need semantic analysis to determine if a type expression is compile-time constant and positive-integer valued.  Perhaps it might be better to defer it to AST generation, and have fewer groups like "simple types" (e.g. `int`, `fixed`, etc) and "compound types" (complex)?

**Comment by taalexander** [comment]
@jakelishman, I think your argument has merits, however, I'll leave this to the grammar WG to decide on how to proceed.

**Comment by jakelishman** [comment]
For sure - definitely not something that needed addressing here.

**Comment by aspcompiler** [comment]
+1 to discuss the refactoring of this part of grammar in grammar WG.

**Pull request merged**
