### PR TITLE
add type field to constant declaration in ast

### PR DESCRIPTION
**Pull request by ajberdy**
### Summary

Add `type` field to `ConstantDeclaration` in `ast.py` to reflect the official grammar. Modify `visitConstantDeclaration` in `qasm_parser.py` to add the type field from the context.

### Details and comments

Bug fix, no open issue found. Tests pass after change.

### CODE REVIEW

**Review by jakelishman — COMMENTED** [review]
The change is good overall, thanks!  Please could you add some tests as well?  I'm not super keen that we didn't catch that this was missing when the grammar was updated, so it'd be good to plug that hole.

**Comment by jwoehr** [comment]
@ajberdy as we are working on a June release, would you care to add test cases so we can merge your PR? Thank you!

**Comment by jwoehr** [comment]
I see there are also conflicts, so some rework may be needed @ajberdy .

**Comment by ajberdy** [comment]
@jwoehr this issue was fixed [283](https://github.com/Qiskit/openqasm/pull/283) with as seen [here](https://github.com/Qiskit/openqasm/commit/303cad9097f17a41926e51273844734dc0e59fe5#diff-37b20aea867626af2c9d599b315c21e169c0404011a18ee64477adfb117dbd19R620)

**Comment by jwoehr** [comment]
thank you, sir

**Pull request closed without merging**
