### PR TITLE
Remove fixed type from openqasm 3

### PR DESCRIPTION
**Pull request by mbhealy**
### Summary
The Types and Casting Work Group ran into many problems when trying to define specific casting rules related to the fixed-point type and conversions to other types. We then stepped back and considered whether the fixed-point type `fixed` was even really necessary. We have yet to find an example of a significant problem that it solves that cannot be worked around with other language features.

### Details and comments

This PR removes the `fixed` type from the specification, grammar, tests, and examples.

### CODE REVIEW

**Review by taalexander — COMMENTED** [review]
If no major counter example can be found this is something I am very much in favour of.

**Comment by jakelishman** [comment]
Aww, thanks for taking care of the syntax highlighter as well!

I don't know about anyone else, but I can't think of any realistic use-cases where you wouldn't be able to use a combination of `float`, `int` and (possibly) `duration` (`dt`, mostly) to achieve compatible results.

**Review by levbishop — DISMISSED** [review]

**Review by blakejohnson — DISMISSED** [review]

**Comment by stevenheidel** [comment]
I believe this was approved by the TSC, pending @blakejohnson review

**Comment by blakejohnson** [comment]
> I believe this was approved by the TSC, pending @blakejohnson review

I thought I had already approved it?

**Review by blakejohnson — APPROVED** [review]

**Pull request merged**
